name: test-test-test
favicon: null
layout_spectrum: 0.40702122915536165
typography_spectrum: 0.5694801472127438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7149757975712419
  lightness: 0.9904046733863652
  saturation: 0.14874824113212526
  rhythmicContrast: 0.10293311881832778
purpose: []
